In [3]:
import numpy as np
from numpy.random import rand
import pickle
import os

wdir = 'C:/ ... /'   # insert path here   
os.chdir(wdir)


blok = np.zeros(2500).reshape(-1,2500)
    
def x():
    read_name = 'Ising0'+str(i)+'.pkl'
    data  = pickle.load(open(read_name,'rb'))
    return np.unpackbits(data).astype(int).reshape(-1, 2500)

    
for i in (1, 5, 9):
    blok = np.vstack((blok, x()))
    print(blok.shape)
    
print('\n', blok)

blok = np.delete(blok, 0, axis = 0)
blok[np.where(blok==-1)]=0
blok = blok.astype('int')
print('\n', '100%, blok.shape:', blok.shape)
name = '3_states.pkl'
pickle.dump(np.packbits(blok), open(name,'wb'))

(10001, 2500)
(20001, 2500)
(30001, 2500)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 1. 1.]
 [0. 1. 0. ... 1. 1. 1.]]

 100%, blok.shape: (30000, 2500)
