In [2]:
# DATA GENERATION ---> PICKLE DUMP
# One of the oldest files, could use some refreshment.
from __future__ import division
import os
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt
from ipywidgets import FloatProgress
from IPython.display import display
import time
import pickle

%matplotlib inline
dir = 'C:/ ... /'     #insert path here!        
wdir = 'C:/ ... /'     #insert path here!'       
os.chdir(wdir)

Tmin = 232 #starting temperature
Tmax = 232 #final temperature
Tloops = 10 # 
Tsteps = 1000 # t_advancement
N = 50

#A = FloatProgress(min=0, max=Tmax, description='A: current temperature.', step = 1/Tmax)
B = FloatProgress(min=0, max=Tloops, description='B: Tloop', step = 1/Tloops)
C = FloatProgress(min=0, max=Tsteps, description='C: Tstep', step = 1/Tsteps)
#D = FloatProgress(min=0, max=N**2, description='D: SPAM', step = 1/N**2)
display(B, C)

#BF = FloatProgress(min=0, max=Tmax, description='Big loop', step = 1/Tmax)
#SF = FloatProgress(min=0, max=Tsteps, description='Small loop', step = 1/Tsteps)

blok = np.zeros(N**2).reshape(-1,N**2)
config = 2*np.random.randint(2, size=(N,N))-1

for a in range(Tmin, Tmax+1): #ZAKRES TEMPERATUR : Tmin/100 do Tmax/100
    
    start = time.time()
    temp = a * 0.01
    beta = 1.0 / temp
    print(temp)
    blok = np.zeros(N**2).reshape(-1,N**2)
    
    for b in range(Tloops):                      #ILE CHCESZ PETLI CZASOWYCH
        
        B.value += 1
        if B.value == Tloops : B.value = 0
        
        config = 2*np.random.randint(2, size=(N,N))-1
        
        for c in range(Tsteps):                          #ILE KROKOW POSTEPU CZASOWEGO 

            C.value += 1
            if C.value == Tsteps : C.value = 0

            for d in range(N**2):      #LOKALNE LOSOWANIE PO 2D LATTICE - POSZCZEGOLNE PIXELE
                
                a = np.random.randint(N)  # wylosuj wspolrzedna z przedzialu                   
                b = np.random.randint(N)  # wylosuj wspolrzedna z przedzialu                    
                s =  config[a, b]            #'numpy.int32'
                nb = config[(a+1)%N,b]+ config[a,(b+1)%N]+ config[(a-1)%N,b]+ config[a,(b-1)%N]
                cost = 2*s*nb

                if cost < 0:
                                s *= -1

                elif rand() < np.exp(-cost*beta):
                                s *= -1

                config[a, b] = s

            if c > Tsteps-11 :
                rconf = config.reshape(-1, N**2)
                blok = np.vstack((blok, rconf))
                #print(blok.shape, blok, type(blok))
    
    #config.reshape(-1, N**2)
    #blok = np.vstack((blok, rconf))
    #print(blok.shape, blok, type(blok))
    
    blok = np.delete(blok, 0, axis = 0)
    blok[np.where(blok==-1)]=0
    blok = blok.astype('int')
    print(blok, blok.shape)
    name = 'T='+str(temp)+'.pkl'
    pickle.dump(np.packbits(blok), open(name,'wb'))
    end = time.time()
    
    miensko = end - start
    print (miensko, 's')

FloatProgress(value=0.0, description='B: Tloop', max=10.0)

FloatProgress(value=0.0, description='C: Tstep', max=1000.0)

2.32
[[1 0 0 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 1 ... 1 1 0]] (100, 2500)
305.40298104286194 s
